[#88] 방 상세 조회
f-lab-edu/airjnc pull request #93
Opened 2022-08-19 06:43 UTC by memoer

### Related Issues

- Resolved #88 

# Description

해당 PR을 하려는 이유를 간단하게 적어주세요

# 변경 사항

변경 사항들을 적어주세요

# 질문 사항

질문 사항들을 적어주세요

# 기타

그 외로 적고 싶은 내용을 적어주세요

# (Optaionl) 어떻게 테스트하셨나요?

2022-08-20 18:51 UTC, f-lab-michael commented on src/main/java/com/airjnc/room/dao/impl/MybatisRoomRepository.java
> +  public RoomDetailResp findById(Long id) {
이 클래스를 Room으로 하고 list에서 쓰는 간단한 정보를 SimpleRoom정도로 하면 좋을것 같습니다.

2022-08-21 09:15 UTC, memoer commented on src/main/java/com/airjnc/room/dao/impl/MybatisRoomRepository.java
> +  public RoomDetailResp findById(Long id) {
넵. 변경하였습니다.

2022-08-24 10:43 UTC, f-lab-michael approved these changes

2022-08-24 10:43 UTC, f-lab-michael requested changes
충돌 해결해주세요~

2022-08-24 10:55 UTC, merged

2022-08-24 10:55 UTC, memoer commented
해결했습니다.